language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - jruby-head
  - jruby-19mode
  - jruby-18mode

before_install:
  - gem update --system
  - gem version

before_script:
  - bundle exec rake db:create db:migrate

bundler_args: --without development production
